# =============================================================================
# TERROIR — Dashboard data-ingestion bootstrap
# Script: bootstrap.py
# Stage:  Dashboard (Fase 5)
# Author: Gabriela Olivera | Data Analytics Portfolio
# =============================================================================
"""
Auto-ingestion bootstrap for Streamlit Cloud deployment. Imported and
called by streamlit_app.py before any page loads.

Local dev workflow is unchanged: data/processed/terroir.db and
parcels_linz.geojson are normally generated by running src/01-08
manually (see data/processed/README.md) — once both exist on disk,
ensure_data() below is a no-op (two Path.exists() calls) on every run,
local or Cloud.

Streamlit Cloud has no persistent volume carried over from a prior
manual run, so the first cold start after a deploy would otherwise
crash every page immediately (no terroir.db to query). This runs the
same 8 ingestion scripts (01-08) as a one-time setup step instead.
00_explore_volumes.py is deliberately excluded — exploratory only, not
part of the pipeline (see its own docstring and src/README.md).

API keys: 01_ingest_linz.py/02_ingest_soil_lcdb.py/03_ingest_subzones.py
each call `load_dotenv()` then read `os.environ["LINZ_API_KEY"]` /
`os.environ["LRIS_API_KEY"]` — confirmed by reading each script, not
assumed. `load_dotenv()` is a silent no-op when no `.env` file exists
(python-dotenv's documented behaviour), so on Streamlit Cloud — where
Secrets are injected straight into the process environment, not as a
`.env` file — those `os.environ[...]` lookups already resolve
correctly with no script changes needed. `.env` is a local-dev-only
convenience; nothing here depends on it existing.

Known limitation, accepted rather than engineered around: the
existence check below covers the *first* pipeline output
(parcels_linz.geojson, from script 01) and *a* early one (terroir.db,
first created by script 02) — not a "pipeline fully completed" marker.
If script 08 (the last one) fails after 01-07 already succeeded, both
checked files already exist, so a restart would skip re-ingestion and
leave `suitability_levels_summary`/`expansion_candidates` missing —
breaking Overview and Expansion Candidates specifically. Not mitigated
here (would need a separate completion marker/lock file, out of the
scope asked for); flagged so it's a known tradeoff, not a silent gap.
"""

import subprocess
import sys
from pathlib import Path

import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

TERROIR_DB = PROCESSED_DIR / "terroir.db"
PARCELS_GEOJSON = PROCESSED_DIR / "parcels_linz.geojson"

# 00_explore_volumes.py excluded on purpose — see module docstring.
PIPELINE_SCRIPTS = [
    "01_ingest_linz.py",
    "02_ingest_soil_lcdb.py",
    "03_ingest_subzones.py",
    "04_calculate_score.py",
    "05_subzone_summary.py",
    "06_cross_project_comparison.py",
    "07_ingest_climate_risk.py",
    "08_regional_summary_expansion.py",
]


def data_exists():
    """True if both pipeline outputs are already on disk. Two cheap
    filesystem stats — safe to call on every Streamlit rerun, not just
    once per session."""
    return TERROIR_DB.exists() and PARCELS_GEOJSON.exists()


def _run_pipeline():
    for script in PIPELINE_SCRIPTS:
        script_path = SRC_DIR / script
        print(f"[bootstrap] running {script}...")
        result = subprocess.run(
            [sys.executable, str(script_path)],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        # Streamed to Cloud's own logs (not the dashboard UI) — useful
        # for diagnosing a failed cold start without local repro.
        if result.stdout:
            print(result.stdout)
        if result.returncode != 0:
            if result.stderr:
                print(result.stderr, file=sys.stderr)
            raise RuntimeError(
                f"Bootstrap ingestion failed at {script} (exit code "
                f"{result.returncode}) — see logs above for that "
                f"script's own stderr."
            )
        print(f"[bootstrap] {script} done.")


def ensure_data():
    """Call once, at the top of streamlit_app.py, before pages run.
    No-op if terroir.db and parcels_linz.geojson already exist; runs
    the full 01-08 pipeline under a spinner otherwise."""
    if data_exists():
        return
    with st.spinner("Setting up data — this may take a few minutes on first run..."):
        _run_pipeline()
