# =============================================================================
# TERROIR — Dashboard data-ingestion bootstrap
# Script: bootstrap.py
# Stage:  Dashboard (Fase 5)
# Author: Gabriela Olivera | Data Analytics Portfolio
# =============================================================================
"""
Auto-ingestion bootstrap for Streamlit Cloud deployment. Imported and
called by streamlit_app.py before any page loads.

Local dev workflow is unchanged: data/processed/terroir.db and
parcels_linz.geojson are normally generated by running src/01-08
manually (see data/processed/README.md) — once both exist, with every
table the pipeline produces actually present in terroir.db,
ensure_data() below is a no-op on every run, local or Cloud.

Streamlit Cloud has no persistent volume carried over from a prior
manual run, so the first cold start after a deploy would otherwise
crash every page immediately (no terroir.db to query). This runs the
same 8 ingestion scripts (01-08) as a one-time setup step instead.
00_explore_volumes.py is deliberately excluded — exploratory only, not
part of the pipeline (see its own docstring and src/README.md).

API keys: 01_ingest_linz.py/02_ingest_soil_lcdb.py/03_ingest_subzones.py
each call `load_dotenv()` then read `os.environ["LINZ_API_KEY"]` /
`os.environ["LRIS_API_KEY"]` — confirmed by reading each script, not
assumed. `load_dotenv()` is a silent no-op when no `.env` file exists
(python-dotenv's documented behaviour), so on Streamlit Cloud — where
Secrets are injected straight into the process environment, not as a
`.env` file — those `os.environ[...]` lookups already resolve
correctly with no script changes needed. `.env` is a local-dev-only
convenience; nothing here depends on it existing.

Fixed, previously a known limitation: the first version of this check
covered only *a* pipeline output (terroir.db existing at all, first
created by script 02) rather than the pipeline having actually
finished. If script 08 (the last one) failed after 01-07 already
succeeded, terroir.db already existed but was missing
suitability_levels_summary/expansion_candidates — breaking Overview
and Expansion Candidates specifically, and a restart would have
skipped re-ingestion since the file-existence check alone couldn't
tell the difference. data_exists() below now opens terroir.db and
checks every table the pipeline is supposed to produce is actually
present, not just that the file exists — a partial database is now
correctly treated the same as no database, and triggers a full re-run.
This also covers a stale/incomplete terroir.db left over from an
earlier deploy on Streamlit Cloud (the scenario this fix was written
for): a "Reboot app" from the Cloud dashboard re-executes this check
against whatever database happens to already be there, and now
re-ingests if it's incomplete rather than trusting its mere existence.
"""

import sqlite3
import subprocess
import sys
from pathlib import Path

import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

TERROIR_DB = PROCESSED_DIR / "terroir.db"
PARCELS_GEOJSON = PROCESSED_DIR / "parcels_linz.geojson"

# Every table the pipeline (02-08) is supposed to leave in terroir.db —
# see data/processed/README.md's own table-by-table breakdown.
REQUIRED_TABLES = [
    "parcel_attributes",
    "parcel_scores",
    "subzone_summary",
    "cross_project_comparison",
    "subzone_climate_risk",
    "suitability_levels_summary",
    "expansion_candidates",
]

# 00_explore_volumes.py excluded on purpose — see module docstring.
PIPELINE_SCRIPTS = [
    "01_ingest_linz.py",
    "02_ingest_soil_lcdb.py",
    "03_ingest_subzones.py",
    "04_calculate_score.py",
    "05_subzone_summary.py",
    "06_cross_project_comparison.py",
    "07_ingest_climate_risk.py",
    "08_regional_summary_expansion.py",
]


def _db_has_required_tables():
    """True only if terroir.db exists, opens cleanly, and contains
    every table in REQUIRED_TABLES — not just that the file is
    present. A missing table (partial pipeline run) or an unreadable
    file (corrupt/mid-write) both return False, the same as "no
    database at all" — both cases need a full re-run, not a crash."""
    if not TERROIR_DB.exists():
        return False
    try:
        with sqlite3.connect(TERROIR_DB) as conn:
            existing = {
                row[0]
                for row in conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'"
                )
            }
    except sqlite3.Error as exc:
        print(f"[bootstrap] terroir.db exists but couldn't be read ({exc}) — treating as missing.")
        return False
    missing = set(REQUIRED_TABLES) - existing
    if missing:
        print(f"[bootstrap] terroir.db is missing tables {sorted(missing)} — treating as incomplete.")
        return False
    return True


def data_exists():
    """True only if parcels_linz.geojson is on disk AND terroir.db
    exists with every required table present — not just that both
    files exist. Cheap enough (one filesystem stat + one small SQLite
    query) to call on every Streamlit rerun, not just once per
    session."""
    return PARCELS_GEOJSON.exists() and _db_has_required_tables()


def _run_pipeline():
    for script in PIPELINE_SCRIPTS:
        script_path = SRC_DIR / script
        print(f"[bootstrap] running {script}...")
        result = subprocess.run(
            [sys.executable, str(script_path)],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        # Streamed to Cloud's own logs (not the dashboard UI) — useful
        # for diagnosing a failed cold start without local repro.
        if result.stdout:
            print(result.stdout)
        if result.returncode != 0:
            if result.stderr:
                print(result.stderr, file=sys.stderr)
            raise RuntimeError(
                f"Bootstrap ingestion failed at {script} (exit code "
                f"{result.returncode}) — see logs above for that "
                f"script's own stderr."
            )
        print(f"[bootstrap] {script} done.")


def ensure_data():
    """Call once, at the top of streamlit_app.py, before pages run.
    No-op if data_exists() finds a complete terroir.db (every required
    table) plus parcels_linz.geojson; runs the full 01-08 pipeline
    under a spinner otherwise."""
    if data_exists():
        return
    with st.spinner("Setting up data — this may take a few minutes on first run..."):
        _run_pipeline()
